# Generated by Django 4.2.7 on 2023-12-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='customer name')),
                ('purchase_date', models.DateTimeField()),
                ('purchase_shop', models.CharField(max_length=100, verbose_name='shop')),
                ('qty', models.SmallIntegerField(verbose_name='qty')),
                ('accessories', models.CharField(max_length=300)),
                ('physical_dmg', models.CharField(max_length=255, verbose_name='Physical Damage')),
                ('reason', models.TextField()),
                ('how_happen', models.TextField(blank=True, verbose_name='How to happen?')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productions.product')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_finding', models.TextField()),
                ('checked', models.DateTimeField(auto_now=True)),
                ('final_result', models.CharField(max_length=200)),
                ('fees', models.IntegerField(default=0)),
                ('fees_by', models.CharField(choices=[('cust', 'Customer'), ('comp', 'Company')], default='comp', max_length=40, verbose_name='charged_by')),
                ('is_checked', models.BooleanField(blank=True, default=False, verbose_name='finished')),
                ('approved', models.BooleanField(blank=True, default=False, verbose_name='approved_by')),
                ('is_done', models.BooleanField(blank=True, default=False, verbose_name='finished')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.errorreturn')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.technician')),
            ],
        ),
    ]
