# Generated by Django 4.2.7 on 2023-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(auto_created=True)),
                ('customer', models.CharField(max_length=255, verbose_name='customer name')),
                ('purchase_date', models.DateTimeField()),
                ('purchase_shop', models.CharField(max_length=100, verbose_name='shop')),
                ('code', models.CharField(max_length=30, verbose_name='product code')),
                ('qty', models.SmallIntegerField(verbose_name='qty')),
                ('accessories', models.CharField(max_length=300)),
                ('physical_dmg', models.CharField(max_length=255, verbose_name='Physical Damage')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_finding', models.TextField()),
                ('checked', models.DateTimeField(auto_now=True)),
                ('final_result', models.CharField(choices=[], max_length=200)),
                ('fees', models.IntegerField()),
                ('fees_by', models.CharField(choices=[('cust', 'Customer'), ('comp', 'Company')], max_length=40, verbose_name='charged_by')),
            ],
        ),
    ]
