# Generated by Django 4.2.7 on 2023-11-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreturn',
            name='code',
        ),
        migrations.AddField(
            model_name='errorreturn',
            name='product',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productions.product'),
        ),
        migrations.AlterField(
            model_name='servicing',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicing',
            name='fees_by',
            field=models.CharField(choices=[('cust', 'Customer'), ('comp', 'Company')], default='comp', max_length=40, verbose_name='charged_by'),
        ),
    ]
