# Generated by Django 4.2.7 on 2023-12-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0002_remove_errorreturn_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicing',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.technician'),
        ),
    ]
