# Generated by Django 4.2.7 on 2023-11-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='code')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('product_price', models.IntegerField(verbose_name='price')),
                ('product_warranty', models.IntegerField(choices=[('3', 3), ('6', 6), ('9', 9), ('12', 12), ('15', 15), ('18', 18)], verbose_name='warranty')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Enter the label of specification: ')),
                ('value', models.CharField(max_length=100, verbose_name='Enter the value of the specification: ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productions.product')),
            ],
        ),
    ]
