# Generated by Django 4.2.7 on 2023-12-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('publisher', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_warranty',
            field=models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (9, '9 months'), (12, '12 months'), (15, '15 months'), (18, '18 months'), (21, '21 months')], verbose_name='warranty months'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Feature: '),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=100, verbose_name="Feature's Value: "),
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog', to='productions.catalog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='productions.catalogcategory')),
            ],
        ),
    ]
